#ifndef CONFIG_H
#define CONFIG_H
#define CONFIG_ANDROID 1
#define CONFIG_AVCODEC 1
#define CONFIG_AVFORMAT 1
#define CONFIG_AVUTIL 1
#define CONFIG_AVFILTER 1
#define CONFIG_SWSCALE 1
#define CONFIG_SWRESAMPLE 1
#define CONFIG_AVDEVICE 1
#define HAVE_PTHREADS 1
#endif
